---
- name: install mariadb
  yum:
    name: mariadb
    state: present
- name: install mariadb-server
  yum:
    name: mariadb-server
    state: present
- name: mariadb service initialize
  service:
    name: mariadb
    state: restarted
